import localFont from "next/font/local";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import Header from "./components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <AppRouterCacheProvider>
        <body>
          <Header />
          {children}
        </body>
      </AppRouterCacheProvider>
    </html>
  );
}
